"""initial_schema

Revision ID: 866450ad96ef
Revises: 
Create Date: 2026-07-24 13:58:14.903901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866450ad96ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('input_type', sa.Enum('domain', 'keyword', 'search_term', name='inputtype'), nullable=False),
    sa.Column('input_value', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('queued', 'scraping', 'cleaning', 'done', 'partial', 'failed', name='jobstatus'), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('stage_detail', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('internal_error', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_pages',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=4096), nullable=False),
    sa.Column('domain', sa.String(length=512), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'skipped', name='pagestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structured_results',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('scraped_page_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=True),
    sa.Column('industry', sa.String(length=256), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('contact_email', sa.String(length=512), nullable=True),
    sa.Column('contact_phone', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=1024), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_data_points', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('cleaned', 'needs_review', 'failed', name='resultstatus'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['scraped_page_id'], ['scraped_pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraped_page_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structured_results')
    op.drop_table('scraped_pages')
    op.drop_table('jobs')
    # ### end Alembic commands ###
